version: 2

sources:
  - name: adventure_works
    tables:
      - name: address
      - name: countryregion
      - name: stateprovince
        columns:
          - name: stateprovinceid
            description: "The primary key for this table"
            tests:
                - unique
                - not_null
      - name: product
        columns:
          - name: productid
            description: "The primary key for this table"
            tests:
                - unique
                - not_null
      - name: person
      - name: creditcard
        columns:
          - name: creditcardid
            description: "The primary key for this table"
            tests:
                - unique
                - not_null
      - name: customer
        columns:
          - name: customerid
            description: "The primary key for this table"
            tests:
                - unique
                - not_null
      - name: salesorderdetail
        columns:
          - name: salesorderdetailid
            description: "The primary key for this table"
            tests:
                - unique
                - not_null
          - name: salesorderid
            description: "The primary key for this table"
            tests:
                - not_null
      - name: salesorderheader
        columns:
          - name: salesorderid
            description: "The primary key for this table"
            tests:
                - unique
                - not_null
      - name: salesorderheadersalesreason
        columns:
          - name: salesorderid
            description: "The primary key for this table"
            tests:
                - not_null
          - name: salesreasonid
            description: "The primary key for this table"
            tests:
                - not_null
      - name: salesreason
        columns:
          - name: salesreasonid
            description: "The primary key for this table"
            tests:
                - unique
                - not_null
      - name: store