version: 2

models:
    - name: fact_orders
      description: Tabela Fato relacionada com as dimensões de Pedido e Produto.
      columns:
          - name: orders_fk
            description: "Foreign Key - dim_salesorders to fact_orderproduct"
            tests:
              - relationships:
                  to: ref('dim_salesorders')
                  field: orders_sk
              - unique
              - not null
          - name: product_fk
            description: "Foreign Key - dim_products to fact_orderproduct."
            tests:
              - relationships:
                  to: ref('dim_products')
                  field: product_sk
          - name: unitprice
            description: "Preço unitário do produto"
          - name: OrderQuantity
            description: "Número de unidades contidas no pedido"
          - name: GrossIncome
            description: "Receita Bruta do pedido"
          - name: Discount
            description: "Desconto para aplicar em cima da Receita Bruta"
          - name: NetIncome
            description: "Receita Líquida do pedido, levando em conta os descontos"
    - name: dim_products
      description: Tabela de dimensão contendo informações de número de série, nível de estoque, modelos, medidas e cores.
      columns:
          - name: product_pk
            description: "Primary Key da tabela products"
            tests:
              - not_null
              - unique
          - name: ProductName
            description: "Nome do produto"
          - name: SeriesNumber
            description: "Número de série do produto"
    - name: dim_salesreason
      description: Tabela de dimensão contendo informações sobre o motivo das vendas.
      columns:
          - name: salesreason_pk
            description: "Primary Key da tabela Motivo"
            tests:
              - unique
              - not null
          - name: salesreasonid
            description: "Identificação do motivo da venda"
            tests:
              - not_null
          - name: reasonname
            description: "Motivo da venda"
          - name: reasontype
            description: "Tipo de motivo"
    - name: dim_address
      description: Tabela de dimensão contendo informações sobre a localização.
      columns:
          - name: address_pk
            description: "Primary Key do endereço"
            tests:
              - unique
              - not null
          - name: CityName
            description: "Nome da cidade"
          - name: StateName
            description: "Nome do estado"
          - name: CountryName
            description: "Nome do país"
          - name: addressline1
            description: "Endereço completo"
          - name: postalcode
            description: "Código de localização CEP"
    - name: dim_creditcard
      description: Tabela de dimensão contendo informações sobre os cartões de crédito.
      columns:
          - name: creditcard_pk
            description: "Primary Key da tabela creditcard"
            tests:
              - unique
              - not null
          - name: cardtype
            description: "Tipos de cartões"
    - name: dim_customer
      description: Tabela de dimensão contendo informações sobre os clientes.
      columns:
          - name: customer_pk
            description: "Primary Key da tabela customer"
            tests:
              - unique
              - not null
          - name: businessentityid
          - name: storeid
            description: "Identificação da Loja cliente"
          - name: CustomerName
            description: "Identificação do Cliente Final"